"""Guards on the shape of the migrated schema itself.

These exist because of a specific near-miss. Autogenerating the intake migration
also produced eight `drop_constraint(..., type_='check')` calls against tables it
was not touching: Alembic cannot match a non-native enum CHECK constraint against
model metadata, so it reads every one of them as an orphan and proposes deleting
it. Applying that migration unedited would have stripped the database-level guard
from every enum column in the schema, silently, while all other tests passed.

The inventory below turns that into a failing test. If a future migration drops
a constraint — deliberately or by autogenerate's suggestion — this fails and
says which one.
"""

from __future__ import annotations

import pytest
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from forgelab_api.db.base import Base
from forgelab_api.domains.constants import (
    ArtifactKind,
    AuditAction,
    AuditOutcome,
    ChallengeSource,
    ChallengeState,
    ProjectAction,
    ProjectRole,
    RunState,
    SupportedLanguage,
)
from forgelab_api.domains.identity.models import (
    MembershipStatus,
    PolicyDecisionOutcome,
    RepositoryConnectionStatus,
)

#: Every enum-backed CHECK constraint the schema is expected to carry, mapped to
#: the enum whose values it must permit.
EXPECTED_CHECK_CONSTRAINTS: dict[tuple[str, str], type] = {
    ("project_memberships", "project_role"): ProjectRole,
    ("project_memberships", "membership_status"): MembershipStatus,
    ("repository_connections", "supported_language"): SupportedLanguage,
    ("repository_connections", "repository_connection_status"): RepositoryConnectionStatus,
    ("policy_decisions", "project_action"): ProjectAction,
    ("policy_decisions", "policy_decision_outcome"): PolicyDecisionOutcome,
    ("audit_events", "audit_action"): AuditAction,
    ("audit_events", "audit_outcome"): AuditOutcome,
    ("challenges", "challenge_source"): ChallengeSource,
    ("challenges", "challenge_status"): ChallengeState,
    ("agent_runs", "agent_run_status"): RunState,
    ("artifact_metadata", "artifact_kind"): ArtifactKind,
}

EXPECTED_TABLES = {
    "tenants",
    "users",
    "projects",
    "project_memberships",
    "repository_connections",
    "refresh_sessions",
    "audit_events",
    "policy_decisions",
    "challenges",
    "agent_runs",
    "evaluation_summaries",
    "artifact_metadata",
}


async def _constraint_definitions(session: AsyncSession) -> dict[tuple[str, str], str]:
    result = await session.execute(
        text(
            """
            SELECT conrelid::regclass::text AS table_name,
                   conname AS constraint_name,
                   pg_get_constraintdef(oid) AS definition
            FROM pg_constraint
            WHERE contype = 'c' AND connamespace = 'public'::regnamespace
            """
        )
    )
    return {(row[0], row[1]): row[2] for row in result}


async def test_every_expected_table_exists(db_session: AsyncSession):
    result = await db_session.execute(
        text("SELECT tablename FROM pg_tables WHERE schemaname = 'public'")
    )
    assert EXPECTED_TABLES <= {row[0] for row in result}


@pytest.mark.parametrize(
    ("table", "constraint"), sorted(EXPECTED_CHECK_CONSTRAINTS), ids=lambda v: str(v)
)
async def test_enum_check_constraint_survives_migrations(
    db_session: AsyncSession, table: str, constraint: str
):
    """A missing entry means a migration dropped a guard, probably unintentionally."""
    definitions = await _constraint_definitions(db_session)
    assert (table, constraint) in definitions, (
        f"CHECK constraint {constraint!r} on {table!r} is missing. If a recent "
        "migration was autogenerated, check it for stray drop_constraint calls."
    )


@pytest.mark.parametrize(
    ("table", "constraint"), sorted(EXPECTED_CHECK_CONSTRAINTS), ids=lambda v: str(v)
)
async def test_check_constraint_permits_every_enum_value(
    db_session: AsyncSession, table: str, constraint: str
):
    """The constraint must list exactly the values the Python enum defines.

    Catches the other half of the problem: a constraint that still exists but
    has fallen behind an enum that gained a member.
    """
    definitions = await _constraint_definitions(db_session)
    definition = definitions[(table, constraint)]
    enum_cls = EXPECTED_CHECK_CONSTRAINTS[(table, constraint)]

    for member in enum_cls:
        assert f"'{member.value}'" in definition, (
            f"{constraint} does not permit {member.value!r}; a hand-written "
            "migration is needed whenever an enum gains a member."
        )


async def test_model_metadata_matches_the_expected_table_set():
    """Guards against a model being added without being registered for migration."""
    assert EXPECTED_TABLES <= set(Base.metadata.tables)
