"""intake domain model

Adds challenges, agent_runs, evaluation_summaries, and artifact_metadata.

⚠️ Autogenerate produced eight extra `op.drop_constraint(..., type_='check')`
calls against audit_events, policy_decisions, project_memberships, and
repository_connections. They have been removed by hand.

Alembic cannot match a non-native enum CHECK constraint against model metadata,
so it sees every one of them as an orphan and proposes deleting it. Applying
that would strip the database-level guard from every enum column in the schema —
the guard that has already caught two real bugs in this project. The same
blindness is why adding an enum value needs a hand-written migration.

**Inspect the diff of every autogenerated migration for stray check-constraint
drops before committing it.**

Revision ID: 7df0380a9760
Revises: d70b1f4c9a22
Create Date: 2026-08-15 00:27:30.305069
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "7df0380a9760"
down_revision = "d70b1f4c9a22"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "challenges",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("repository_id", sa.UUID(), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "github_issue",
                "manual",
                "sample",
                name="challenge_source",
                native_enum=False,
                create_constraint=True,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("source_ref", sa.String(length=255), nullable=True),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("source_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "running",
                "evaluating",
                "complete",
                "failed",
                name="challenge_status",
                native_enum=False,
                create_constraint=True,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("agent_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repository_connections.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_challenges_created_at"), "challenges", ["created_at"])
    op.create_index(op.f("ix_challenges_project_id"), "challenges", ["project_id"])
    op.create_index("ix_challenges_project_status", "challenges", ["project_id", "status"])
    op.create_index(op.f("ix_challenges_repository_id"), "challenges", ["repository_id"])
    op.create_index("ix_challenges_tenant_created", "challenges", ["tenant_id", "created_at"])
    op.create_index(op.f("ix_challenges_tenant_id"), "challenges", ["tenant_id"])
    op.create_index(
        "uq_challenges_github_issue",
        "challenges",
        ["project_id", "source_ref"],
        unique=True,
        postgresql_where=sa.text("source_type = 'github_issue'"),
    )

    op.create_table(
        "agent_runs",
        sa.Column("challenge_id", sa.UUID(), nullable=False),
        sa.Column("lane", sa.Integer(), nullable=False),
        sa.Column("agent_key", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                "terminated",
                name="agent_run_status",
                native_enum=False,
                create_constraint=True,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("sandbox_id", sa.String(length=128), nullable=True),
        sa.Column("termination_reason", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["challenge_id"], ["challenges.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("challenge_id", "lane", name="uq_agent_runs_challenge_lane"),
    )
    op.create_index(op.f("ix_agent_runs_challenge_id"), "agent_runs", ["challenge_id"])
    op.create_index("ix_agent_runs_challenge_lane", "agent_runs", ["challenge_id", "lane"])
    op.create_index(op.f("ix_agent_runs_created_at"), "agent_runs", ["created_at"])
    op.create_index(op.f("ix_agent_runs_tenant_id"), "agent_runs", ["tenant_id"])
    op.create_index("ix_agent_runs_tenant_status", "agent_runs", ["tenant_id", "status"])

    op.create_table(
        "artifact_metadata",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("challenge_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "patch",
                "diff",
                "log",
                "test_report",
                "preview",
                name="artifact_kind",
                native_enum=False,
                create_constraint=True,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("uri", sa.String(length=1000), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("checksum", sa.String(length=128), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["challenge_id"], ["challenges.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_artifact_metadata_challenge_id"), "artifact_metadata", ["challenge_id"]
    )
    op.create_index(op.f("ix_artifact_metadata_created_at"), "artifact_metadata", ["created_at"])
    op.create_index("ix_artifact_metadata_run_kind", "artifact_metadata", ["run_id", "kind"])
    op.create_index(op.f("ix_artifact_metadata_tenant_id"), "artifact_metadata", ["tenant_id"])

    op.create_table(
        "evaluation_summaries",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("challenge_id", sa.UUID(), nullable=False),
        sa.Column("tests_passed", sa.Integer(), nullable=False),
        sa.Column("tests_total", sa.Integer(), nullable=False),
        sa.Column("build_passed", sa.Boolean(), nullable=True),
        sa.Column("lint_passed", sa.Boolean(), nullable=True),
        sa.Column("security_findings", sa.Integer(), nullable=True),
        sa.Column("files_changed", sa.Integer(), nullable=True),
        sa.Column("lines_added", sa.Integer(), nullable=True),
        sa.Column("lines_removed", sa.Integer(), nullable=True),
        sa.Column("thresholds_met", sa.Boolean(), nullable=False),
        sa.Column("forge_score", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["challenge_id"], ["challenges.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", name="uq_evaluation_summaries_run"),
    )
    op.create_index(
        op.f("ix_evaluation_summaries_challenge_id"), "evaluation_summaries", ["challenge_id"]
    )
    op.create_index(
        op.f("ix_evaluation_summaries_created_at"), "evaluation_summaries", ["created_at"]
    )
    op.create_index(
        "ix_evaluation_summaries_tenant", "evaluation_summaries", ["tenant_id", "thresholds_met"]
    )
    op.create_index(
        op.f("ix_evaluation_summaries_tenant_id"), "evaluation_summaries", ["tenant_id"]
    )

    # NOTE: autogenerate also emitted drop_constraint calls for audit_action,
    # audit_outcome, policy_decision_outcome, project_action, membership_status,
    # project_role, repository_connection_status, and supported_language.
    # Removed deliberately — see the module docstring.


def downgrade() -> None:
    op.drop_index(op.f("ix_evaluation_summaries_tenant_id"), table_name="evaluation_summaries")
    op.drop_index("ix_evaluation_summaries_tenant", table_name="evaluation_summaries")
    op.drop_index(op.f("ix_evaluation_summaries_created_at"), table_name="evaluation_summaries")
    op.drop_index(op.f("ix_evaluation_summaries_challenge_id"), table_name="evaluation_summaries")
    op.drop_table("evaluation_summaries")

    op.drop_index(op.f("ix_artifact_metadata_tenant_id"), table_name="artifact_metadata")
    op.drop_index("ix_artifact_metadata_run_kind", table_name="artifact_metadata")
    op.drop_index(op.f("ix_artifact_metadata_created_at"), table_name="artifact_metadata")
    op.drop_index(op.f("ix_artifact_metadata_challenge_id"), table_name="artifact_metadata")
    op.drop_table("artifact_metadata")

    op.drop_index("ix_agent_runs_tenant_status", table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_tenant_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_created_at"), table_name="agent_runs")
    op.drop_index("ix_agent_runs_challenge_lane", table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_challenge_id"), table_name="agent_runs")
    op.drop_table("agent_runs")

    op.drop_index(
        "uq_challenges_github_issue",
        table_name="challenges",
        postgresql_where=sa.text("source_type = 'github_issue'"),
    )
    op.drop_index(op.f("ix_challenges_tenant_id"), table_name="challenges")
    op.drop_index("ix_challenges_tenant_created", table_name="challenges")
    op.drop_index(op.f("ix_challenges_repository_id"), table_name="challenges")
    op.drop_index("ix_challenges_project_status", table_name="challenges")
    op.drop_index(op.f("ix_challenges_project_id"), table_name="challenges")
    op.drop_index(op.f("ix_challenges_created_at"), table_name="challenges")
    op.drop_table("challenges")

    # The eight check constraints autogenerate wanted to recreate here were
    # never dropped in upgrade(), so there is nothing to restore.
