"""identity persistence models

Revision ID: 9466ae0563e3
Revises: 
Create Date: 2026-08-14 16:10:18.535399
"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = '9466ae0563e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_tenants_created_at'), 'tenants', ['created_at'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_projects_tenant_slug')
    )
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index('ix_users_tenant_active', 'users', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('challenge_id', sa.UUID(), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('repository.connected', 'challenge.launched', 'agent.rerun_requested', 'result.reviewed', 'result.approved', 'pull_request.created', 'sandbox.created', 'sandbox.destroyed', 'credential.issued', 'credential.revoked', 'run.limit_reached', name='audit_action', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index('ix_audit_events_project_created', 'audit_events', ['project_id', 'created_at'], unique=False)
    op.create_index('ix_audit_events_run', 'audit_events', ['run_id'], unique=False)
    op.create_index('ix_audit_events_tenant_created', 'audit_events', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('policy_decisions',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('challenge_id', sa.UUID(), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('connect_repository', 'launch_challenge', 'rerun_failed_agent', 'review_result', 'approve_result', 'create_pull_request', name='project_action', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('decision', sa.Enum('allow', 'deny', name='policy_decision_outcome', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_decisions_created_at'), 'policy_decisions', ['created_at'], unique=False)
    op.create_index('ix_policy_decisions_project_action', 'policy_decisions', ['project_id', 'action'], unique=False)
    op.create_index('ix_policy_decisions_tenant_created', 'policy_decisions', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_policy_decisions_tenant_id'), 'policy_decisions', ['tenant_id'], unique=False)
    op.create_table('project_memberships',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'maintainer', 'reviewer', 'operator', name='project_role', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('status', sa.Enum('active', 'revoked', name='membership_status', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_memberships_created_at'), 'project_memberships', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_memberships_project_id'), 'project_memberships', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_memberships_tenant_id'), 'project_memberships', ['tenant_id'], unique=False)
    op.create_index('ix_project_memberships_user', 'project_memberships', ['tenant_id', 'user_id'], unique=False)
    op.create_index('uq_project_memberships_active', 'project_memberships', ['project_id', 'user_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('refresh_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_sessions_created_at'), 'refresh_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_refresh_sessions_tenant_id'), 'refresh_sessions', ['tenant_id'], unique=False)
    op.create_index('ix_refresh_sessions_user_expiry', 'refresh_sessions', ['user_id', 'expires_at'], unique=False)
    op.create_table('repository_connections',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('installation_id', sa.String(length=64), nullable=True),
    sa.Column('language', sa.Enum('python', 'nodejs', name='supported_language', native_enum=False, create_constraint=True, length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'connected', 'disconnected', 'error', name='repository_connection_status', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'full_name', name='uq_repository_connections_project_name')
    )
    op.create_index(op.f('ix_repository_connections_created_at'), 'repository_connections', ['created_at'], unique=False)
    op.create_index(op.f('ix_repository_connections_project_id'), 'repository_connections', ['project_id'], unique=False)
    op.create_index(op.f('ix_repository_connections_tenant_id'), 'repository_connections', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repository_connections_tenant_id'), table_name='repository_connections')
    op.drop_index(op.f('ix_repository_connections_project_id'), table_name='repository_connections')
    op.drop_index(op.f('ix_repository_connections_created_at'), table_name='repository_connections')
    op.drop_table('repository_connections')
    op.drop_index('ix_refresh_sessions_user_expiry', table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_tenant_id'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_created_at'), table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.drop_index('uq_project_memberships_active', table_name='project_memberships', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_project_memberships_user', table_name='project_memberships')
    op.drop_index(op.f('ix_project_memberships_tenant_id'), table_name='project_memberships')
    op.drop_index(op.f('ix_project_memberships_project_id'), table_name='project_memberships')
    op.drop_index(op.f('ix_project_memberships_created_at'), table_name='project_memberships')
    op.drop_table('project_memberships')
    op.drop_index(op.f('ix_policy_decisions_tenant_id'), table_name='policy_decisions')
    op.drop_index('ix_policy_decisions_tenant_created', table_name='policy_decisions')
    op.drop_index('ix_policy_decisions_project_action', table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_created_at'), table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_tenant_created', table_name='audit_events')
    op.drop_index('ix_audit_events_run', table_name='audit_events')
    op.drop_index('ix_audit_events_project_created', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index('ix_users_tenant_active', table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_tenants_created_at'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
