"""Add outcome, reason, and request_id to audit_events

Written by hand rather than autogenerated: Alembic does not detect drift in
non-native enum CHECK constraints, so neither the new `audit_outcome`
constraint nor the added `session.denied` value on `audit_action` would appear
in a generated diff. See migration a1c4e77b21d5 for the same trap.

`outcome` is nullable so rows written before this migration remain valid. Every
write through the audit writer sets it; a NULL means "written before WO-006",
not "unknown outcome".

Revision ID: c93f2a5e08b7
Revises: a1c4e77b21d5
"""

import sqlalchemy as sa
from alembic import op

revision = "c93f2a5e08b7"
down_revision = "a1c4e77b21d5"
branch_labels = None
depends_on = None

TABLE_NAME = "audit_events"

AUDIT_ACTION_CONSTRAINT = "audit_action"
AUDIT_OUTCOME_CONSTRAINT = "audit_outcome"

PREVIOUS_ACTIONS = (
    "repository.connected",
    "challenge.launched",
    "agent.rerun_requested",
    "result.reviewed",
    "result.approved",
    "pull_request.created",
    "sandbox.created",
    "sandbox.destroyed",
    "credential.issued",
    "credential.revoked",
    "run.limit_reached",
    "session.issued",
    "session.refreshed",
    "session.revoked",
    "session.replay_detected",
)

NEW_ACTIONS = ("session.denied",)

OUTCOMES = ("permit", "deny", "failure", "system")


def _in_clause(column: str, values: tuple[str, ...]) -> str:
    rendered = ", ".join(f"'{value}'" for value in values)
    return f"{column} IN ({rendered})"


def upgrade() -> None:
    op.add_column(TABLE_NAME, sa.Column("outcome", sa.String(length=64), nullable=True))
    op.add_column(TABLE_NAME, sa.Column("reason", sa.Text(), nullable=True))
    op.add_column(TABLE_NAME, sa.Column("request_id", sa.String(length=64), nullable=True))

    # Permit NULL for pre-existing rows while constraining every value written.
    op.create_check_constraint(
        AUDIT_OUTCOME_CONSTRAINT,
        TABLE_NAME,
        sa.text(f"outcome IS NULL OR {_in_clause('outcome', OUTCOMES)}"),
    )

    op.drop_constraint(AUDIT_ACTION_CONSTRAINT, TABLE_NAME, type_="check")
    op.create_check_constraint(
        AUDIT_ACTION_CONSTRAINT,
        TABLE_NAME,
        sa.text(_in_clause("action", PREVIOUS_ACTIONS + NEW_ACTIONS)),
    )

    op.create_index("ix_audit_events_request", TABLE_NAME, ["request_id"])
    op.create_index("ix_audit_events_action_outcome", TABLE_NAME, ["action", "outcome"])


def downgrade() -> None:
    op.drop_index("ix_audit_events_action_outcome", table_name=TABLE_NAME)
    op.drop_index("ix_audit_events_request", table_name=TABLE_NAME)

    # Rows using the newly added action would violate the narrower constraint.
    # Deleting audit rows is lossy; that is the honest cost of going backwards.
    op.execute(sa.text(f"DELETE FROM {TABLE_NAME} WHERE {_in_clause('action', NEW_ACTIONS)}"))  # noqa: S608
    op.drop_constraint(AUDIT_ACTION_CONSTRAINT, TABLE_NAME, type_="check")
    op.create_check_constraint(
        AUDIT_ACTION_CONSTRAINT,
        TABLE_NAME,
        sa.text(_in_clause("action", PREVIOUS_ACTIONS)),
    )

    op.drop_constraint(AUDIT_OUTCOME_CONSTRAINT, TABLE_NAME, type_="check")
    op.drop_column(TABLE_NAME, "request_id")
    op.drop_column(TABLE_NAME, "reason")
    op.drop_column(TABLE_NAME, "outcome")
